/*
 * defaultConfigJson.h
 *
 *  Created on: May 10, 2013
 *      Author: brent
 */

#ifndef DEFAULTCONFIGJSON_H_
#define DEFAULTCONFIGJSON_H_


const char *defaultConfig =
		"{"
			"\"gpsConfig\" : {"
				"\"gpsInstalled\" : 1,"
				"\"startFinishTarget\" : {"
					"\"latitude\" : 0,"
					"\"longitude\" : 0,"
					"\"targetRadius\" : 0.0004"
				"},"
				"\"splitTarget\" : {"
					"\"latitude\" : 0,"
					"\"longitude\" : 0,"
					"\"targetRadius\" : 0.0004"
				"},"
				"\"latitude\" : {"
					"\"label\" : \"Latitude\","
					"\"units\" : \"Deg\","
					"\"sampleRate\" : 10"
				"},"
				"\"longitude\" : {"
					"\"label\" : \"Longitude\","
					"\"units\" : \"Deg\","
					"\"sampleRate\" : 10"
				"},"
				"\"speed\" : {"
					"\"label\" : \"Speed\","
					"\"units\" : \"MPH\","
					"\"sampleRate\" : 10"
				"},"
				"\"time\" : {"
					"\"label\" : \"Time\","
					"\"units\" : \"Time\","
					"\"sampleRate\" : 1"
				"},"
				"\"satellites\" : {"
					"\"label\" : \"GpsSats\","
					"\"units\" : \"\","
					"\"sampleRate\" : 0"
				"},"
				"\"lapCount\" : {"
					"\"label\" : \"LapCount\","
					"\"units\" : \"\","
					"\"sampleRate\" : 0"
				"},"
				"\"lapTime\" : {"
					"\"label\" : \"LapTime\","
					"\"units\" : \"seconds\","
					"\"sampleRate\" : 0"
				"},"
				"\"splitTime\" : {"
					"\"label\" : \"SplitTime\","
					"\"units\" : \"seconds\","
					"\"sampleRate\" : 0"
				"}"
			"},"
			"\"analogConfigs\" : ["
				"{"
					"\"channelConfig\" : {"
						"\"label\" : \"Analog1\","
						"\"units\" : \"Units\","
						"\"sampleRate\" : 0"
					"},"
					"\"loggingPrecision\" : 2,"
					"\"linearScaling\" : 0.0049,"
					"\"scalingMode\" : 1,"
					"\"scalingMap\" : ["
						"{"
							"\"raw\" : 0,"
							"\"scaled\" : 0"
						"},"
						"{"
							"\"raw\" : 256,"
							"\"scaled\" : 1.25"
						"},"
						"{"
							"\"raw\" : 512,"
							"\"scaled\" : 2.5"
						"},"
						"{"
							"\"raw\" : 768,"
							"\"scaled\" : 3.75"
						"},"
						"{"
							"\"raw\" : 1023,"
							"\"scaled\" : 5"
						"}"
					"]"
				"},"
				"{"
					"\"channelConfig\" : {"
						"\"label\" : \"Analog2\","
						"\"units\" : \"Units\","
						"\"sampleRate\" : 0"
					"},"
					"\"loggingPrecision\" : 2,"
					"\"linearScaling\" : 0.0049,"
					"\"scalingMode\" : 1,"
					"\"scalingMap\" : ["
						"{"
							"\"raw\" : 0,"
							"\"scaled\" : 0"
						"},"
						"{"
							"\"raw\" : 256,"
							"\"scaled\" : 1.25"
						"},"
						"{"
							"\"raw\" : 512,"
							"\"scaled\" : 2.5"
						"},"
						"{"
							"\"raw\" : 768,"
							"\"scaled\" : 3.75"
						"},"
						"{"
							"\"raw\" : 1023,"
							"\"scaled\" : 5"
						"}"
					"]"
				"},"
				"{"
					"\"channelConfig\" : {"
						"\"label\" : \"Analog3\","
						"\"units\" : \"Units\","
						"\"sampleRate\" : 0"
					"},"
					"\"loggingPrecision\" : 2,"
					"\"linearScaling\" : 0.0049,"
					"\"scalingMode\" : 1,"
					"\"scalingMap\" : ["
						"{"
							"\"raw\" : 0,"
							"\"scaled\" : 0"
						"},"
						"{"
							"\"raw\" : 256,"
							"\"scaled\" : 1.25"
						"},"
						"{"
							"\"raw\" : 512,"
							"\"scaled\" : 2.5"
						"},"
						"{"
							"\"raw\" : 768,"
							"\"scaled\" : 3.75"
						"},"
						"{"
							"\"raw\" : 1023,"
							"\"scaled\" : 5"
						"}"
					"]"
				"},"
				"{"
					"\"channelConfig\" : {"
						"\"label\" : \"Analog4\","
						"\"units\" : \"Units\","
						"\"sampleRate\" : 0"
					"},"
					"\"loggingPrecision\" : 2,"
					"\"linearScaling\" : 0.0049,"
					"\"scalingMode\" : 1,"
					"\"scalingMap\" : ["
						"{"
							"\"raw\" : 0,"
							"\"scaled\" : 0"
						"},"
						"{"
							"\"raw\" : 256,"
							"\"scaled\" : 1.25"
						"},"
						"{"
							"\"raw\" : 512,"
							"\"scaled\" : 2.5"
						"},"
						"{"
							"\"raw\" : 768,"
							"\"scaled\" : 3.75"
						"},"
						"{"
							"\"raw\" : 1023,"
							"\"scaled\" : 5"
						"}"
					"]"
				"},"
				"{"
					"\"channelConfig\" : {"
						"\"label\" : \"Analog5\","
						"\"units\" : \"Units\","
						"\"sampleRate\" : 0"
					"},"
					"\"loggingPrecision\" : 2,"
					"\"linearScaling\" : 0.0049,"
					"\"scalingMode\" : 1,"
					"\"scalingMap\" : ["
						"{"
							"\"raw\" : 0,"
							"\"scaled\" : 0"
						"},"
						"{"
							"\"raw\" : 256,"
							"\"scaled\" : 1.25"
						"},"
						"{"
							"\"raw\" : 512,"
							"\"scaled\" : 2.5"
						"},"
						"{"
							"\"raw\" : 768,"
							"\"scaled\" : 3.75"
						"},"
						"{"
							"\"raw\" : 1023,"
							"\"scaled\" : 5"
						"}"
					"]"
				"},"
				"{"
					"\"channelConfig\" : {"
						"\"label\" : \"Analog6\","
						"\"units\" : \"Units\","
						"\"sampleRate\" : 0"
					"},"
					"\"loggingPrecision\" : 2,"
					"\"linearScaling\" : 0.0049,"
					"\"scalingMode\" : 1,"
					"\"scalingMap\" : ["
						"{"
							"\"raw\" : 0,"
							"\"scaled\" : 0"
						"},"
						"{"
							"\"raw\" : 256,"
							"\"scaled\" : 1.25"
						"},"
						"{"
							"\"raw\" : 512,"
							"\"scaled\" : 2.5"
						"},"
						"{"
							"\"raw\" : 768,"
							"\"scaled\" : 3.75"
						"},"
						"{"
							"\"raw\" : 1023,"
							"\"scaled\" : 5"
						"}"
					"]"
				"},"
				"{"
					"\"channelConfig\" : {"
						"\"label\" : \"Analog7\","
						"\"units\" : \"Units\","
						"\"sampleRate\" : 0"
					"},"
					"\"loggingPrecision\" : 2,"
					"\"linearScaling\" : 0.0049,"
					"\"scalingMode\" : 1,"
					"\"scalingMap\" : ["
						"{"
							"\"raw\" : 0,"
							"\"scaled\" : 0"
						"},"
						"{"
							"\"raw\" : 256,"
							"\"scaled\" : 1.25"
						"},"
						"{"
							"\"raw\" : 512,"
							"\"scaled\" : 2.5"
						"},"
						"{"
							"\"raw\" : 768,"
							"\"scaled\" : 3.75"
						"},"
						"{"
							"\"raw\" : 1023,"
							"\"scaled\" : 5"
						"}"
					"]"
				"},"
				"{"
					"\"channelConfig\" : {"
						"\"label\" : \"Battery\","
						"\"units\" : \"Volts\","
						"\"sampleRate\" : 0"
					"},"
					"\"loggingPrecision\" : 2,"
					"\"linearScaling\" : 0.0171,"
					"\"scalingMode\" : 1,"
					"\"scalingMap\" : ["
						"{"
							"\"raw\" : 0,"
							"\"scaled\" : 0"
						"},"
						"{"
							"\"raw\" : 256,"
							"\"scaled\" : 1.25"
						"},"
						"{"
							"\"raw\" : 512,"
							"\"scaled\" : 2.5"
						"},"
						"{"
							"\"raw\" : 768,"
							"\"scaled\" : 3.75"
						"},"
						"{"
							"\"raw\" : 1023,"
							"\"scaled\" : 5"
						"}"
					"]"
				"}"
			"],"
			"\"pulseInputConfigs\" : ["
				"{"
					"\"channelConfig\" : {"
						"\"label\" : \"RPM\","
						"\"units\" : \"RPM\","
						"\"sampleRate\" : 0"
					"},"
					"\"loggingPrecision\" : 0,"
					"\"slowTimer\" : 0,"
					"\"mode\" : 0,"
					"\"pulsePerRev\" : 1,"
					"\"timerDivider\" : 128,"
					"\"scaling\" : 375428"
				"},"
				"{"
					"\"channelConfig\" : {"
						"\"label\" : \"Freq2\","
						"\"units\" : \"Hz\","
						"\"sampleRate\" : 0"
					"},"
					"\"loggingPrecision\" : 0,"
					"\"slowTimer\" : 0,"
					"\"mode\" : 1,"
					"\"pulsePerRev\" : 1,"
					"\"timerDivider\" : 128,"
					"\"scaling\" : 375428"
				"},"
				"{"
					"\"channelConfig\" : {"
						"\"label\" : \"Freq3\","
						"\"units\" : \"Hz\","
						"\"sampleRate\" : 0"
					"},"
					"\"loggingPrecision\" : 0,"
					"\"slowTimer\" : 0,"
					"\"mode\" : 1,"
					"\"pulsePerRev\" : 1,"
					"\"timerDivider\" : 128,"
					"\"scaling\" : 375428"
				"}"
			"],"
			"\"accelConfigs\" : ["
				"{"
					"\"channelConfig\" : {"
						"\"label\" : \"AccelX\","
						"\"units\" : \"G\","
						"\"sampleRate\" : 30"
					"},"
					"\"mode\" : 1,"
					"\"mapping\" : 0,"
					"\"zeroValue\" : 2048"
				"},"
				"{"
					"\"channelConfig\" : {"
						"\"label\" : \"AccelY\","
						"\"units\" : \"G\","
						"\"sampleRate\" : 30"
					"},"
					"\"mode\" : 1,"
					"\"mapping\" : 1,"
					"\"zeroValue\" : 2048"
				"},"
				"{"
					"\"channelConfig\" : {"
						"\"label\" : \"AccelZ\","
						"\"units\" : \"G\","
						"\"sampleRate\" : 30"
					"},"
					"\"mode\" : 1,"
					"\"mapping\" : 2,"
					"\"zeroValue\" : 2048"
				"},"
				"{"
					"\"channelConfig\" : {"
						"\"label\" : \"Yaw\","
						"\"units\" : \"Deg/Sec\","
						"\"sampleRate\" : 30"
					"},"
					"\"mode\" : 1,"
					"\"mapping\" : 3,"
					"\"zeroValue\" : 1862"
				"}"
			"],"
			"\"pulseOutputConfigs\" : ["
				"{"
					"\"channelConfig\" : {"
						"\"label\" : \"Vout1\","
						"\"units\" : \"V\","
						"\"sampleRate\" : 0"
					"},"
					"\"loggingPrecision\" : 2,"
					"\"outputMode\" : 0,"
					"\"loggingMode\" : 2,"
					"\"startupDutyCycle\" : 50,"
					"\"startupPeriod\" : 100,"
					"\"voltageScaling\" : 0.1"
				"},"
				"{"
					"\"channelConfig\" : {"
						"\"label\" : \"Vout2\","
						"\"units\" : \"V\","
						"\"sampleRate\" : 0"
					"},"
					"\"loggingPrecision\" : 2,"
					"\"outputMode\" : 0,"
					"\"loggingMode\" : 0,"
					"\"startupDutyCycle\" : 50,"
					"\"startupPeriod\" : 100,"
					"\"voltageScaling\" : 0.1"
				"},"
				"{"
					"\"channelConfig\" : {"
						"\"label\" : \"Vout3\","
						"\"units\" : \"V\","
						"\"sampleRate\" : 0"
					"},"
					"\"loggingPrecision\" : 2,"
					"\"outputMode\" : 0,"
					"\"loggingMode\" : 1,"
					"\"startupDutyCycle\" : 50,"
					"\"startupPeriod\" : 100,"
					"\"voltageScaling\" : 0.1"
				"},"
				"{"
					"\"channelConfig\" : {"
						"\"label\" : \"Vout4\","
						"\"units\" : \"V\","
						"\"sampleRate\" : 0"
					"},"
					"\"loggingPrecision\" : 2,"
					"\"outputMode\" : 0,"
					"\"loggingMode\" : 0,"
					"\"startupDutyCycle\" : 50,"
					"\"startupPeriod\" : 100,"
					"\"voltageScaling\" : 0.1"
				"}"
			"],"
			"\"gpioConfigs\" : ["
				"{"
					"\"channelConfig\" : {"
						"\"label\" : \"GPIO1\","
						"\"units\" : \"\","
						"\"sampleRate\" : 0"
					"},"
					"\"mode\" : 0"
				"},"
				"{"
					"\"channelConfig\" : {"
						"\"label\" : \"GPIO2\","
						"\"units\" : \"\","
						"\"sampleRate\" : 0"
					"},"
					"\"mode\" : 0"
				"},"
				"{"
					"\"channelConfig\" : {"
						"\"label\" : \"GPIO3\","
						"\"units\" : \"\","
						"\"sampleRate\" : 0"
					"},"
					"\"mode\" : 0"
				"}"
			"],"
			"\"outputConfig\" : {"
				"\"sdLoggingMode\" : 1,"
				"\"telemetryMode\" : 0,"
				"\"telemetryServer\" : \"54.245.229.2\","
				"\"telemetryDeviceId\" : \"\","
				"\"p2pDestAddrHigh\" : 0,"
				"\"p2pDestAddrLow\" : 65535"
			"},"
			"\"automation\" : {"
				"\"script\" : \"function onTick() end\""
			"}"
		"}";


#endif /* DEFAULTCONFIGJSON_H_ */
